on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Baixar dados
        run: |-
          curl "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson" | jq > usgs.json

      - name: Commit e Push
        run: |-
          git config user.name "saulofender"
          git config user.email "salomao.valentim@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Atualizado em: ${timestamp}" || exit 0
          git push
