name: Scrape data

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Baixar dados
        run: |-
          curl "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson" | jq > usgs.json
      
      - name: Commit e Push
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Atualizado em: ${timestamp}" || exit 0
          git push
